# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: judge_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13judge_service.proto\"\x1d\n\x0fJudgeServiceReq\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\x0fJudgeServiceRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x42\n\x0cJudgeService\x12\x32\n\nGetFeature\x12\x10.JudgeServiceReq\x1a\x10.JudgeServiceRsp\"\x00\x62\x06proto3')



_JUDGESERVICEREQ = DESCRIPTOR.message_types_by_name['JudgeServiceReq']
_JUDGESERVICERSP = DESCRIPTOR.message_types_by_name['JudgeServiceRsp']
JudgeServiceReq = _reflection.GeneratedProtocolMessageType('JudgeServiceReq', (_message.Message,), {
  'DESCRIPTOR' : _JUDGESERVICEREQ,
  '__module__' : 'judge_service_pb2'
  # @@protoc_insertion_point(class_scope:JudgeServiceReq)
  })
_sym_db.RegisterMessage(JudgeServiceReq)

JudgeServiceRsp = _reflection.GeneratedProtocolMessageType('JudgeServiceRsp', (_message.Message,), {
  'DESCRIPTOR' : _JUDGESERVICERSP,
  '__module__' : 'judge_service_pb2'
  # @@protoc_insertion_point(class_scope:JudgeServiceRsp)
  })
_sym_db.RegisterMessage(JudgeServiceRsp)

_JUDGESERVICE = DESCRIPTOR.services_by_name['JudgeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JUDGESERVICEREQ._serialized_start=23
  _JUDGESERVICEREQ._serialized_end=52
  _JUDGESERVICERSP._serialized_start=54
  _JUDGESERVICERSP._serialized_end=87
  _JUDGESERVICE._serialized_start=89
  _JUDGESERVICE._serialized_end=155
# @@protoc_insertion_point(module_scope)
